modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/ErzeKawek/EdenRing-Reforked/issues"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
description="Sci-fi dimension mod with unique world generation, flora, structures and creatures."
authors="paulevs, y3z0n, Firel, ErzeKawek, ChristopherJ123, OpenBagTwo"
displayURL="https://modrinth.com/mod/eden-ring-reforked"
logoFile="assets/edenring/icon.png"

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="[${forge_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft_version}]"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="bclib"
mandatory=true
versionRange="[${bclib_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="wunderlib"
mandatory=true
versionRange="[${wunderlib_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="jei"
mandatory=false
versionRange="[1.0,)"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="jade"
mandatory=false
versionRange="[1.0,)"
ordering="NONE"
side="CLIENT"

[[mixins]]
config="edenring.mixins.common.json"

[[mixins]]
config="edenring.mixins.client.json"
